version: '3.8'
services:
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    ports:
      - "7071:4242"
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL}
    command: tail -f /dev/null  # Keep the container running for manual intervention
  strapi:
    build:
      context: ./packages/blog-cms
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
      - DATABASE_SSL_STRICT=${DATABASE_SSL_STRICT}
      - DATABASE_CA_CERT=${DATABASE_CA_CERT}
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  notifications:
    build:
      context: ./packages/notifications
      dockerfile: Dockerfile
    ports:
      - "4300:4300"
    environment:
      - NODE_ENV=production
      - SERVICE_WEB_PUBSUB_CONNECTION_STRING=${SERVICE_WEB_PUBSUB_CONNECTION_STRING}
  blog:
    build:
      context: ./packages/blog
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - WEB_APP_URL=${WEB_APP_URL}
